# Generated by Django 4.1.4 on 2022-12-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_remove_gallery_images_image_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
