# Generated by Django 4.1.4 on 2022-12-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0006_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='col_sm',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='col_xl',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='col_xs',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
