# Generated by Django 4.1.4 on 2022-12-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0007_gallery_col_sm_gallery_col_xl_gallery_col_xs'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='size_style',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='slide_style',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
