# Generated by Django 4.1.4 on 2022-12-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0008_gallery_size_style_gallery_slide_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='height',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='width',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
