# Generated by Django 4.1.4 on 2022-12-22 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0010_bookings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='service',
        ),
    ]
