# Generated by Django 4.1.4 on 2022-12-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0011_remove_bookings_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
