# Generated by Django 4.1.4 on 2022-12-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0012_bookings_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='service',
            field=models.CharField(blank=True, choices=[('Party', 'Party'), ('Dine-In', 'Dine-In'), ('Carry-Out', 'Carry-Out'), ('Event Catering', 'Event Catering')], max_length=100, null=True),
        ),
    ]
