# Generated by Django 4.1.4 on 2022-12-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0014_service_alter_bookings_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(choices=[('Party', 'Party'), ('Dine-In', 'Dine-In'), ('Carry-Out', 'Carry-Out'), ('Event Catering', 'Event Catering')], default='Party', max_length=100),
        ),
    ]
