# Generated by Django 4.1.4 on 2022-12-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0020_alter_settings_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='logo_inverse',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
