# Generated by Django 4.1.4 on 2022-12-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0022_aboutus_history_team_settings_image_about1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='style_delay',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='style_tabs',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='experience',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='sub_topic',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='history',
            name='detail',
            field=models.CharField(max_length=400),
        ),
    ]
