# Generated by Django 4.1.4 on 2022-12-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0025_iconclassic'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='delay',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
