# Generated by Django 4.1.4 on 2022-12-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0027_team_email_team_facebook_team_instagram_team_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='active',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='show',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='style_delay',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='style_tabs',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
