# Generated by Django 4.1.4 on 2022-12-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0029_remove_history_style_delay_alter_settings_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='settings',
            name='image_about3',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
    ]
