# Generated by Django 4.1.4 on 2022-12-25 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0031_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='./images/user.png', null=True, upload_to='images/users/'),
        ),
    ]
