# Generated by Django 4.1.4 on 2022-12-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0032_alter_userprofile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/users/'),
        ),
    ]
