# Generated by Django 4.1.4 on 2022-12-25 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0036_alter_comment_user_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
