# Generated by Django 4.1.4 on 2022-12-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0039_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='show',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='style_delay',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='style_tabs',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
