# Generated by Django 4.1.4 on 2022-12-28 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0043_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='image_about1',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='image_about2',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='image_about3',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='image_background',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='image_home1',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='image_home2',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='logo_inverse',
        ),
    ]
